/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikopikomazorkito;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/**
 *
 * @author carlos-pc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private ImageIcon img;

    public VentanaPrincipal() {
        initComponents();
        this.setResizable(false); //Que la ventana no se redimensione
        this.setBounds(200, 150, 901, 600);
        this.setTitle("Picko Picko Mazorkito");
        this.img = new ImageIcon("res/bg.jpg");
        this.etiquetaImagen.setIcon(this.img);
        this.etiquetaImagen.setText("");
        this.etiquetaImagen.setSize(901, 600);
        
    try {

            new JFXPanel();
            String pon = new File("res/sonidos/musicaprincipal.mp3").toURI().toString();
            new MediaPlayer(new Media(pon)).play();
        } catch (Exception e) {
            System.out.println("No se puede iniciar");
        }   
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJugar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        etiquetaImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 23, 700, 1000));
        setUndecorated(true);
        getContentPane().setLayout(null);

        botonJugar.setBackground(new java.awt.Color(255, 255, 255));
        botonJugar.setIcon(new javax.swing.ImageIcon("res/botones/Jugar.png")); // NOI18N
        botonJugar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonJugar.setRolloverIcon(new javax.swing.ImageIcon("res/botones/JugarR.png")); // NOI18N
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(botonJugar);
        botonJugar.setBounds(670, 150, 160, 50);

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon("res/botones/Salir.png")); // NOI18N
        botonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonSalir.setRolloverIcon(new javax.swing.ImageIcon("res/botones/SalirR.png")); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(670, 280, 160, 50);

        etiquetaImagen.setText("Bienvenido a Piko Piko Mazorquito");
        getContentPane().add(etiquetaImagen);
        etiquetaImagen.setBounds(0, 0, 980, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO Añadir el método que permita seleccionar el número de jugadores

        //Aquí esta el JOption con los jugadores que se crean
        Integer[] jugadores = {2, 3, 4};

        Object opcion = JOptionPane.showInputDialog(null, "¿Cuantos jugadores van a jugar?", "Elegir", JOptionPane.QUESTION_MESSAGE, null, jugadores, jugadores[0]);

        int gamers = (int) opcion;
        
        //Creación del Arraylist
        ArrayList<Jugador> ludopatas = new ArrayList();
        
        //Dado el número de jugadores que vamos a tener
        //Procedemos a preguntar sus nombre
        for (int i = 0; i < gamers; i++) {
            String texto;
            
            //Bucle do para tener si ó si un nombre
            do {
                texto = JOptionPane.showInputDialog("Introduce el nombre del jugador " + (i + 1));

            } while (texto.isEmpty());

            ludopatas.add(new Jugador(texto));
        }
        
        //Imprimo por consola todos los jugadores que ha introducido su nombre
        ludopatas.forEach(System.out::println);
        
        new VentanaJuego(ludopatas).setVisible(true);
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Cierra la aplicación
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaImagen;
    // End of variables declaration//GEN-END:variables

}
