/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikopikomazorkito;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos-pc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private ImageIcon img;

    public VentanaPrincipal() {
        initComponents();
        this.setResizable(false); //Que la ventana no se redimensione
        this.setBounds(400, 150, 1200, 800);
        this.setTitle("Picko Picko Mazorkito");
        this.setBackground(Color.WHITE);
        this.img = new ImageIcon("res/bg.jpg");
        this.etiquetaImagen.setIcon(this.img);
        this.etiquetaImagen.setText("");
        this.etiquetaImagen.setSize(1200, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJugar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        etiquetaImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 23, 700, 1000));
        setUndecorated(true);
        getContentPane().setLayout(null);

        botonJugar.setBackground(new java.awt.Color(255, 255, 255));
        botonJugar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Now_m\\Documents\\NetBeansProjects\\PikoPikoMazorkitos\\res\\botones\\Jugar.png")); // NOI18N
        botonJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(botonJugar);
        botonJugar.setBounds(870, 270, 210, 50);

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Now_m\\Documents\\NetBeansProjects\\PikoPikoMazorkitos\\res\\botones\\Salir.png")); // NOI18N
        botonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(870, 420, 210, 50);

        etiquetaImagen.setText("Bienvenido a Piko Piko Mazorquito");
        getContentPane().add(etiquetaImagen);
        etiquetaImagen.setBounds(0, 0, 520, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO Añadir el método que permita seleccionar el número de jugadores

        //Aquí esta el JOption con los jugadores que se crean
        Integer[] jugadores = {2, 3, 4};

        Object opcion = JOptionPane.showInputDialog(null, "¿Cuantos jugadores van a jugar?", "Elegir", JOptionPane.QUESTION_MESSAGE, null, jugadores, jugadores[0]);

        int gamers = (int) opcion;

        Jugador[] jugones = new Jugador[gamers];

        for (int i = 0; i < jugones.length; i++) {
            String texto = JOptionPane.showInputDialog("Digame el nombre del jugador " + (i + 1));
            jugones[i] = new Jugador(texto);
        }

        //Imprimo los jugadores por si sale algún fallo pero los crea perfectamente
        for (Jugador aux : jugones) {
            System.out.println(aux);
        }

        switch(gamers){
            case 2:
                new VentanaJuego(2, jugones[0], jugones[1]).setVisible(true);
                break;
            case 3:
                new VentanaJuego(3, jugones[0], jugones[1], jugones[2]).setVisible(true);
                break;
            case 4:
                new VentanaJuego(4, jugones[0], jugones[1], jugones[2], jugones[3]).setVisible(true);
                break;
        }
        


    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Cierra la aplicación
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaImagen;
    // End of variables declaration//GEN-END:variables

}
